export const FETCH_PRECIPITATIONS = "FETCH_PRECIPITATIONS",
    FETCH_CURRENT_WEATHER = "FETCH_CURRENT_WEATHER",
    FETCH_FB_SOILSENSOR = "FETCH_FB_SOILSENSOR",
    FETCH_CURRENT_USER = "FETCH_CURRENT_USER";
